// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjeiMyIRJIV22JShKnWbJY2G77sACN2Is',
    appId: '1:872720522034:web:4045b5bfdfde1d1868952b',
    messagingSenderId: '872720522034',
    projectId: 'raqibusman1',
    authDomain: 'raqibusman1.firebaseapp.com',
    storageBucket: 'raqibusman1.firebasestorage.app',
    measurementId: 'G-N086HHZMF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUcCy29SeUewDyisiVa9DwxUBqZlWOS0Q',
    appId: '1:872720522034:android:2a98159fd46ced2f68952b',
    messagingSenderId: '872720522034',
    projectId: 'raqibusman1',
    storageBucket: 'raqibusman1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSWeiqsjkcRwaOw_twqGeoqzCj1kEl5-o',
    appId: '1:872720522034:ios:4d3535fffad18a3d68952b',
    messagingSenderId: '872720522034',
    projectId: 'raqibusman1',
    storageBucket: 'raqibusman1.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );
}
